<a href="https://colab.research.google.com/github/avineses/PUC_DBDC/blob/main/Clase2/Clase_2_02_listas_y_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Ángel Ubilla Vera <br>
**E-mail ayudante:** rumorale1@gmail.com


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto). 
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [3]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista
lista1 <- list(num = 10,
letra = c("a","b","c"),
mat = diag(99,3),
l = list(a=100, b=c(T,F,F)), 1989)
lista1


$num
[1] 10

$letra
[1] "a" "b" "c"

$mat
     [,1] [,2] [,3]
[1,]   99    0    0
[2,]    0   99    0
[3,]    0    0   99

$l
$l$a
[1] 100

$l$b
[1]  TRUE FALSE FALSE


[[5]]
[1] 1989

In [4]:
str(lista1)

List of 5
 $ num  : num 10
 $ letra: chr [1:3] "a" "b" "c"
 $ mat  : num [1:3, 1:3] 99 0 0 0 99 0 0 0 99
 $ l    :List of 2
  ..$ a: num 100
  ..$ b: logi [1:3] TRUE FALSE FALSE
 $      : num 1989


In [ ]:
# estructura


In [8]:
# Podemos guardar los objetos en slots con nombres
lista2 <- list("X","Y")

In [9]:
# Podemos combinar listas
c(lista1,lista2)

$num
[1] 10

$letra
[1] "a" "b" "c"

$mat
     [,1] [,2] [,3]
[1,]   99    0    0
[2,]    0   99    0
[3,]    0    0   99

$l
$l$a
[1] 100

$l$b
[1]  TRUE FALSE FALSE


[[5]]
[1] 1989

[[6]]
[1] "X"

[[7]]
[1] "Y"

In [5]:
# Acceso mediante posición
lista1[3]

$mat
     [,1] [,2] [,3]
[1,]   99    0    0
[2,]    0   99    0
[3,]    0    0   99

In [ ]:
lista1[3] #retorna una lista de largo 1 con una matriz en esa entrada
lista2[]

In [ ]:
#Podemos rescatar el elemento (3,3) de la matriz alojada en el "slot" de posicion 3.
lista1[]

In [ ]:
# NOTA lista[.] retorna un lista con un elemento,
# lista[[.]] retorna el elmento de la lista lista[.]



In [ ]:
# de la lista l3[[5]], quieo el vector que está en el slot llamado "b" (segundo elemento)


In [ ]:
# Acceso mediante nombre



In [ ]:
# acceso vía "$" para acceder directamente al elemento del slot citado.

lista1$mat





In [ ]:
# para saber el largo de la lista/vector
length(lista1)

# Para obtener los nombres de la lista
names(lista1)
# si quisiéramos renombrar los slots:


In [11]:
# También podemos crear nuevos "slots"
## Indicando nombre en [[]] y luego asignando
lista1[["nuevo"]] <- as.Date("2022-04-13")
lista1

$num
[1] 10

$letra
[1] "a" "b" "c"

$mat
     [,1] [,2] [,3]
[1,]   99    0    0
[2,]    0   99    0
[3,]    0    0   99

$l
$l$a
[1] 100

$l$b
[1]  TRUE FALSE FALSE


[[5]]
[1] 1989

$nuevo
[1] "2022-04-13"

In [13]:
lista1$nuevo2 <- "Hola soy yo de nuevo"
lista1

$num
[1] 10

$letra
[1] "a" "b" "c"

$mat
     [,1] [,2] [,3]
[1,]   99    0    0
[2,]    0   99    0
[3,]    0    0   99

$l
$l$a
[1] 100

$l$b
[1]  TRUE FALSE FALSE


[[5]]
[1] 1989

$nuevo
[1] "2022-04-13"

$nuevo2
[1] "Hola soy yo de nuevo"

In [ ]:
# podemos modificar elementos dentro de un slot



### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí. 

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.
 
 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [16]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)

df <- data.frame(nombre = c("miguel","jorge","cony"),
          edad=c(33,30,32),
          fn=c(1989,1992,1990))


In [17]:
df

nombre edad fn  
1 miguel 33   1989
2 jorge  30   1992
3 cony   32   1990

In [18]:
# Acceso a columnas de un data.frame
## Igual que en una lista
df["edad"]
df[["edad"]]


edad
1 33  
2 30  
3 32

[1] 33 30 32

In [19]:
#Se heredan propiedades de una matriz
dim(df)

[1] 3 3

In [22]:
##  Ganamos acceso como matriz
# segundafila de df
df[2,]

# segunda columna y segunda fila
df[2,2]
df[2,"edad"]



nombre edad fn  
2 jorge  30   1992

[1] 30

[1] 30

In [24]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista
df$genero <- c("M","M","F")
df

nombre edad fn   genero
1 miguel 33   1989 M     
2 jorge  30   1992 M     
3 cony   32   1990 F

In [26]:
#Otra forma de agregar columna:
df[["tiene_hijos"]] <- c(F,T,F)
df

nombre edad fn   genero tiene_hijos
1 miguel 33   1989 M      FALSE      
2 jorge  30   1992 M       TRUE      
3 cony   32   1990 F      FALSE

In [28]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar nombre y tiene hijos.
df[c(1,5)]
df[c("nombre","tiene_hijos")]
# Referenciando el nombre de las columnas


nombre tiene_hijos
1 miguel FALSE      
2 jorge   TRUE      
3 cony   FALSE

nombre tiene_hijos
1 miguel FALSE      
2 jorge   TRUE      
3 cony   FALSE

In [ ]:
#Queremos de esta tabla todas las columnas pero sólo las filas donde la columna edad sea mayor o igual a 32.
df$edad >= 32

In [32]:
df[df$edad >= 32, c("nombre","genero")]
df[df$edad >= 32,] [c("nombre","genero")]

nombre genero
1 miguel M     
3 cony   F

nombre genero
1 miguel M     
3 cony   F

In [ ]:
# Referenciando las posiciones de las columnas


In [ ]:
# Se mantiene la lógica de acceso a los sots de una lista.
