<a href="https://colab.research.google.com/github/avineses/PUC_DBDC/blob/main/Clase2/Clase_2_01_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Ángel Ubilla Vera <br>
**E-mail ayudante:** rumorale1@gmail.com



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una maztriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo. 
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.
 
 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [7]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos
A <- matrix(c(11,12,13,14,15,16),ncol=3)
A


[,1] [,2] [,3]
[1,] 11   13   15  
[2,] 12   14   16

In [3]:
B <- matrix(c(11,12,13,14,15,16), ncol = 3, byrow = T)
B

[,1] [,2] [,3]
[1,] 11   12   13  
[2,] 14   15   16

In [6]:
# clase y atributo dim
class(A)
dim(A)

[1] "matrix" "array"

[1] 2 3

In [8]:
# Genere dos vectores del mismo largo y forme una matriz.
f1 <- c("a","b","c")
f2 <- c("x","y","z")


In [9]:
# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind
cbind(f1,f2)
rbind(f1,f2)


f1 f2
[1,] a  x 
[2,] b  y 
[3,] c  z

[,1] [,2] [,3]
f1 a    b    c   
f2 x    y    z

In [23]:
# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)

L= rbind(f1,c("m","n"))
L


Warning message in rbind(f1, c("m", "n")):
“number of columns of result is not a multiple of vector length (arg 2)”


[,1] [,2] [,3]
f1 a    b    c   
   m    n    m

In [12]:
# función diag para la definición de matrices diagonales
#?diag 

diag(10,4)


[,1] [,2] [,3] [,4]
[1,] 10    0    0    0  
[2,]  0   10    0    0  
[3,]  0    0   10    0  
[4,]  0    0    0   10

In [14]:
# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# Ejemplo:

# quiero rescatar el elemento "(2,1)"
A[2,1]

# CUIDADO:No es lo mismo que 
A[c(2,1)] # R entiende también la matriz como un gran vector (por columnas) y lo anterior retorna los elmentos 2 y 1 de dicho vector

[1] 12

[1] 12 11

In [16]:
# Para acceder a una fila completa
A[2,]


# Para acceder a una columna completa
A[,3]


[1] 12 14 16

[1] 15 16

In [17]:
#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el 14 por un 99 (el 14 de la pos 2,2)
A[2,2] <- 99
A

[,1] [,2] [,3]
[1,] 11   13   15  
[2,] 12   99   16

In [ ]:
# Nombres de filas y columnas
rownames(L)
colnames(L)

In [25]:
colnames (L) <- c("c1","c2","c3")
L

c1 c2 c3
f1 a  b  c 
   m  n  m

In [26]:
# Acceso mediante nombres
L["f1","c2"]
L[2,2]

[1] "b"

[1] "n"

In [ ]:
M2

In [27]:
# Acceso mediante nomnbres
L["f1",]

c1  c2  c3 
"a" "b" "c"

In [28]:
# Acceso mediante "indicatrices" lógicas 
#Quiero obtener los elementos (1,1) y (2,3) de M2
# 1: Crear una matriz de 2x3 con TRUE en dichas posiciones y FALSE en las restantes.

m_ind <- matrix(c(T,F,F,F,F,T),ncol= 3, byrow = T)
m_ind

[,1]  [,2]  [,3] 
[1,]  TRUE FALSE FALSE
[2,] FALSE FALSE  TRUE

In [ ]:
# Podemos evaluar las casillas de una atriz mediante sentencias lógicas
L[m_ind]

In [30]:
L[L %in% c("a","z")]

[1] "a"

**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [ ]:
# transponer una matriz


In [ ]:
# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices



In [ ]:
# Multiplicación de matrices
M2 * M1 # multiplicación componente a componente


In [ ]:
# podemos calcular determinantes
# ?det



In [ ]:
# Podemos invertir matrices
# ?solve
